version: "2"

run:
  timeout: 5m

linters:
  enable:
    # Core linters (enabled by default anyway)
    - errcheck       # Check for unchecked errors
    - govet          # Vet examines Go source code  
    - ineffassign    # Detect ineffectual assignments
    - staticcheck    # Advanced static analysis
    - unused         # Check for unused code
    # Additional useful linters
    - misspell       # Fix spelling mistakes
    - gosec          # Security issues

linters-settings:
  govet:
    enable:
      - shadow  # Check for shadowed variables
  misspell:
    locale: US

issues:
  exclude-rules:
    # Package comments are overkill for small utility libraries
    - linters: [staticcheck]  
      text: "at least one file in a package should have a package comment"